version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: store_backend
    networks:
      - shared_network
    build: ./backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  shared_network:
    external: true
